#路由：给一个字符串，解析之后，根据结果路径、分发请求内容、应用哪个服务
server:
  port: 8083
spring:
  application:
    name: GATWEAYSERVER
  cloud:
    gateway:
      routes:
        - id: applyconsumer
          predicates:
            - Path= /apply/**
          uri: lb://APPLYCONSUMER
        - id: applyprovider
          predicates:
            - Path=/dao/**
          uri: lb://APPLYPROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8080/eureka/
