server:
  port: 8082
spring:
  application:
    name: APPLYPROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8080/eureka/
#    APPLYPROVIDER: # 编写调用服务名称
#      ribbon:
#        NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule